name: Django CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3307:3306  # 3307 포트를 사용
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oz_django

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3307  # DB 포트 설정
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: oz_django

    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run black
        run: |
          poetry run black . --check

      - name: Run isort
        run: |
          poetry run isort . --check --diff

      - name: Run Mypy
        run: |
          poetry run mypy .

      - name: Test python project
        run: |
          poetry run python manage.py test
